source:
    host: 172.29.254.22
    port: 1521
    user: qatestw
    password: qatestw
    service: qatest
    schema: ''

destination:
    host: localhost
    port: 9042
    type: cassandra
    keyspace: mic

params:
    company: 90
    plant: 01
    import_country: DE
    language: ENG
    data: 'data'
    month_from: 01
    year_from: 2018

logging:
    version: 1
    formatters:
        detailed:
            class: 'logging.Formatter'
            format: "%(asctime)s %(name)-15s %(levelname)-8s %(processName)-10s %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
        file_handler:
            class: logging.handlers.RotatingFileHandler
            filename: mic.log
            level: DEBUG
            formatter: detailed
            mode: w
    loggers:
        mic.oracle:
            level: WARN
            # handlers: [console, file_handler]
            handlers: [file_handler]
            propagate: no
        '':
            level: INFO # ERROR WARN INFO DEBUG
            handlers: [file_handler]