M.format_grid=M.format_grid||{ourYUI:null,editing_on:null,section_redirect:null,selected_section:null,num_sections:null,selected_section_no:-1,shadebox_shown_array:null,shadebox_content:null,rtl:!1};M.format_grid.init=function(Y,the_editing_on,the_section_redirect,the_num_sections,the_shadebox_shown_array,the_rtl){"use strict";this.ourYUI=Y;this.editing_on=the_editing_on;this.section_redirect=the_section_redirect;this.selected_section=null;this.num_sections=parseInt(the_num_sections);this.shadebox_shown_array=the_shadebox_shown_array;this.rtl=the_rtl;Y.use('json-parse',function(Y){M.format_grid.shadebox_shown_array=Y.JSON.parse(M.format_grid.shadebox_shown_array)});if(this.num_sections>0){this.set_selected_section(this.num_sections,!0,!0)}else{this.selected_section_no=-1}
if(the_editing_on){Y.all(".grid_section").removeClass('hide_section')}else{Y.delegate('click',this.icon_click,Y.config.doc,'ul.gridicons a.gridicon_link',this);var shadeboxtoggleone=Y.one("#gridshadebox_overlay");if(shadeboxtoggleone){shadeboxtoggleone.on('click',this.icon_toggle,this)}
var shadeboxtoggletwo=Y.one("#gridshadebox_close");if(shadeboxtoggletwo){shadeboxtoggletwo.on('click',this.icon_toggle,this);document.getElementById("gridshadebox_close").style.display=""}
var shadeboxarrowleft=Y.one("#gridshadebox_left");if(shadeboxarrowleft){shadeboxarrowleft.on('click',this.arrow_left,this);document.getElementById("gridshadebox_left").style.display=""}
var shadeboxarrowright=Y.one("#gridshadebox_right");if(shadeboxarrowright){shadeboxarrowright.on('click',this.arrow_right,this);document.getElementById("gridshadebox_right").style.display=""}
var gridiconcontainer=Y.one("#gridiconcontainer");var icon_links=gridiconcontainer.all("a.gridicon_link");icon_links.each(function(node){node.setAttribute("href","#")});M.format_grid.shadebox.initialize_shadebox();M.format_grid.shadebox.update_shadebox();window.onresize=function(){M.format_grid.shadebox.update_shadebox()}}
this.shadebox_content=Y.one("#gridshadebox_content");this.shadebox_content.removeClass('hide_content')};M.format_grid.icon_click=function(e){"use strict";e.preventDefault();var icon_index=parseInt(e.currentTarget.get('id').replace("gridsection-",""));var previous_no=this.selected_section_no;this.selected_section_no=icon_index;this.update_selected_background(previous_no);this.icon_toggle(e)};M.format_grid.tab=function(index){"use strict";this.ourYUI.log('M.format_grid.tab: '+index);var previous_no=this.selected_section_no;this.selected_section_no=index;this.update_selected_background(previous_no);if(M.format_grid.shadebox.shadebox_open==!0){this.change_shown()}};M.format_grid.icon_toggle=function(e){"use strict";e.preventDefault();if(this.selected_section_no!=-1){if((this.editing_on==!0)&&(this.update_capability==!0)){window.scroll(0,document.getElementById("section-"+this.selected_section_no).offsetTop)}else if(this.section_redirect!==null){location.replace(this.section_redirect+"&section="+this.selected_section_no)}else if(M.format_grid.shadebox.shadebox_open==!0){this.shadebox.toggle_shadebox()}else{this.change_shown();this.shadebox.toggle_shadebox()}}};M.format_grid.arrow_left=function(e){"use strict";if(this.rtl){this.change_selected_section(!0)}else{this.change_selected_section(!1)}};M.format_grid.arrow_right=function(e){"use strict";if(this.rtl){this.change_selected_section(!1)}else{this.change_selected_section(!0)}};M.format_grid.change_selected_section=function(increase_section){"use strict";if(this.selected_section_no!=-1){this.set_selected_section(this.selected_section_no,increase_section,!1);if(M.format_grid.shadebox.shadebox_open==!0){this.change_shown()}}};M.format_grid.change_shown=function(){"use strict";if(this.selected_section!=null){this.selected_section.addClass('hide_section')}
this.selected_section=this.ourYUI.one("#section-"+this.selected_section_no);var firstactivity=document.getElementById("section-"+this.selected_section_no).getElementsByTagName('a')[0];if(firstactivity){firstactivity.focus()}
this.selected_section.removeClass('hide_section')};M.format_grid.set_selected_section=function(starting_point,increase_section,initialise){"use strict";if((this.selected_section_no!=-1)||(initialise==!0)){var previous_no=this.selected_section_no;this.selected_section_no=this.find_next_shown_section(starting_point,increase_section);this.update_selected_background(previous_no)}};M.format_grid.update_selected_background=function(previous_no){"use strict";if(this.selected_section_no!=-1){var selected_section=this.ourYUI.one("#gridsection-"+this.selected_section_no);selected_section.get('parentNode').addClass('currentselected')}
if((previous_no!=-1)&&(previous_no!=this.selected_section_no)){var previous_section=this.ourYUI.one("#gridsection-"+previous_no);previous_section.get('parentNode').removeClass('currentselected')}};M.format_grid.find_next_shown_section=function(starting_point,increase_section){"use strict";var found=!1;var current=starting_point;var next=starting_point;while(found==!1){if(increase_section==!0){current++;if(current>this.num_sections){current=0}}else{current--;if(current<0){current=this.num_sections}}
if(current==starting_point){found=!0}else if(this.shadebox_shown_array[current]==2){next=current;found=!0}}
return next};M.format_grid.shadebox=M.format_grid.shadebox||{shadebox_open:null,shadebox_overlay:null,grid_shadebox:null};M.format_grid.shadebox.initialize_shadebox=function(){"use strict";this.shadebox_open=!1;this.shadebox_overlay=document.getElementById('gridshadebox_overlay');this.shadebox_overlay.style.display="";this.grid_shadebox=document.getElementById('gridshadebox');document.body.appendChild(this.grid_shadebox);this.hide_shadebox();var top=50;var mainregion=M.format_grid.ourYUI.one('#region-main');if(mainregion){var mainregionDOM=mainregion.getDOMNode();top=mainregionDOM.offsetTop+mainregionDOM.clientTop+15}
var content=document.getElementById('gridshadebox_content');content.style.position='absolute';content.style.width='90%';content.style.top=''+top+'px';content.style.left='5%';content.style.zIndex='1'};M.format_grid.shadebox.toggle_shadebox=function(){"use strict";if(this.shadebox_open){this.hide_shadebox();this.shadebox_open=!1}else{window.scrollTo(0,0);this.show_shadebox();this.shadebox_open=!0}};M.format_grid.shadebox.show_shadebox=function(){"use strict";this.update_shadebox();this.grid_shadebox.style.display=""};M.format_grid.shadebox.hide_shadebox=function(){"use strict";this.grid_shadebox.style.display="none"};M.format_grid.shadebox.update_shadebox=function(){"use strict";var pagesize=this.get_page_height();this.shadebox_overlay.style.height=pagesize+"px"};M.format_grid.shadebox.get_page_height=function(){"use strict";var yScroll;if(window.innerHeight&&window.scrollMaxY){yScroll=window.innerHeight+window.scrollMaxY}else if(document.body.scrollHeight>document.body.offsetHeight){yScroll=document.body.scrollHeight}else{yScroll=document.body.offsetHeight}
var windowHeight;if(self.innerHeight){windowHeight=self.innerHeight}else if(document.documentElement&&document.documentElement.clientHeight){windowHeight=document.documentElement.clientHeight}else if(document.body){windowHeight=document.body.clientHeight}
var pageHeight;if(yScroll<windowHeight){pageHeight=windowHeight}else{pageHeight=yScroll}
return pageHeight}