FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS builder

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln .
#RUN echo $(pwd)
#COPY Tadeot.Registration/*.csproj ./Tadeot.Registration/
#COPY Tadeot.Photos/Tadeot.Photos.csproj ./Tadeot.Registration/
###COPY Tadeot.Core/*.csproj ./Tadeot.Registration/
#COPY Tadeot.Persistence/*.csproj ./Tadeot.Registration/
#COPY Utils/*.csproj ./Tadeot.Registration/
#COPY Tadeot.Visitors.Web/*.csproj ./Tadeot.Registration/
#COPY Tadeot.Webstats/*.csproj ./Tadeot.Registration/
#COPY Tadeot.Feedback.Web/*.csproj ./Tadeot.Registration/
#RUN cd ./Tadeot.Registration \
 #   && echo $(ls) \
 #   && echo $(pwd) \
 #   && cd ..

#RUN dotnet restore

# Copy everything else and build
COPY . ./
WORKDIR /app/Tadeot.Registration
EXPOSE 80
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
EXPOSE 80
COPY --from=builder /app/Tadeot.Registration/out .
ENTRYPOINT ["dotnet", "Tadeot.Registration.dll"]
