version: '3'
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    expose: 
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - visualizationNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    depends_on: 
      - elasticsearch
    links: 
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks: 
      - visualizationNetwork
  
networks:
  visualizationNetwork:
    driver: bridge
  
    