# Display name of the action
name: Gradle-Tests
# Defines when the action should run
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

# Definition of what should be done
jobs:
  gradle:
    runs-on: ubuntu-latest # The task should be executed on an ubuntu env.
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: extract-transform/generator-gerald
          wrapper-directory: extract-transform/generator-gerald
          arguments: test
